package translate

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestIsMostlyChinese(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		{"Apple unveils M5 chip, 40% faster", false},
		{"苹果发布 M5 芯片，性能提升 40%", true},
		// A Chinese headline routinely carries a Latin product name; the 30% ratio
		// exists so those still count as Chinese.
		{"OpenAI 发布新模型", true},
		// The reverse: an English headline with one Chinese term must still be sent.
		{"Xiaomi ships the 小米 15 to Europe this quarter", false},
		// No letters at all — nothing a translation would change.
		{"2026 :: 40% !!", true},
		{"", true},
	}
	for _, c := range cases {
		if got := IsMostlyChinese(c.in); got != c.want {
			t.Errorf("IsMostlyChinese(%q) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestCleanStripsWrappers(t *testing.T) {
	in := "Apple unveils M5 chip"
	cases := []struct{ raw, want string }{
		{`苹果发布 M5 芯片`, "苹果发布 M5 芯片"},
		{`"苹果发布 M5 芯片"`, "苹果发布 M5 芯片"},
		{"  “苹果发布 M5 芯片”  ", "苹果发布 M5 芯片"},
		{"「苹果发布 M5 芯片」", "苹果发布 M5 芯片"},
		{"", ""},
	}
	for _, c := range cases {
		if got := clean(c.raw, in); got != c.want {
			t.Errorf("clean(%q) = %q, want %q", c.raw, got, c.want)
		}
	}
}

// Quotes inside a headline are punctuation, not a wrapper, and must survive.
//
// These are real rows from the deployed DB, produced when clean() trimmed a
// cutset of quote characters off both ends unconditionally: a translation ending
// in a quoted phrase lost its closer and kept a dangling opener, and one opening
// with a quotation lost its opener. Only a matching pair at both ends is a
// wrapper.
func TestCleanKeepsQuotesInsideTheHeadline(t *testing.T) {
	cases := []struct{ name, raw, in, want string }{{
		name: "closing quote at the end is not a wrapper",
		raw:  "莱茵金属CEO对失去海军合同“非常不满”",
		in:   "Rheinmetall CEO 'Very Unhappy' With Naval Contract Loss",
		want: "莱茵金属CEO对失去海军合同“非常不满”",
	}, {
		name: "opening quote at the start is not a wrapper",
		raw:  "“机不可失”：欧盟真的准备接纳新成员吗？",
		in:   "'It's now or never.' Is the EU serious about letting in new members?",
		want: "“机不可失”：欧盟真的准备接纳新成员吗？",
	}, {
		name: "a real wrapper is still removed",
		raw:  "“苹果发布 M5 芯片”",
		in:   "Apple unveils M5 chip",
		want: "苹果发布 M5 芯片",
	}, {
		name: "nested wrappers unwind",
		raw:  `"「苹果发布 M5 芯片」"`,
		in:   "Apple unveils M5 chip",
		want: "苹果发布 M5 芯片",
	}, {
		name: "mismatched ends are left alone",
		raw:  "“苹果发布 M5 芯片」",
		in:   "Apple unveils M5 chip",
		want: "“苹果发布 M5 芯片」",
	}}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := clean(c.raw, c.in); got != c.want {
				t.Fatalf("clean(%q) = %q, want %q", c.raw, got, c.want)
			}
		})
	}
}

// The demonstration turns are the fix for the model mirroring the labelled form
// back. They must be on the wire, in order, with the real request last — and they
// must be generated by userMessage, or the model would be shown a format that can
// drift from the one it is actually sent.
func TestRequestCarriesExampleTurns(t *testing.T) {
	var got chatRequest
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewDecoder(r.Body).Decode(&got)
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"choices":[{"message":{"content":"苹果发布 M5 芯片"}}]}`))
	}))
	defer srv.Close()
	cfg := Config{BaseURL: srv.URL, APIKey: "sk-test", Model: "m"}

	real := Request{Title: "Apple unveils M5 chip", FeedName: "Ars Technica"}
	if _, err := New(nil).Translate(context.Background(), cfg, real); err != nil {
		t.Fatalf("Translate: %v", err)
	}

	// system + one user/assistant pair per example + the real request.
	wantLen := 2 + 2*len(examplePairs)
	if len(got.Messages) != wantLen {
		t.Fatalf("sent %d messages, want %d", len(got.Messages), wantLen)
	}
	if got.Messages[0].Role != "system" || got.Messages[0].Content != systemPrompt {
		t.Fatal("first message is not the system prompt")
	}
	for i, e := range examplePairs {
		user, assistant := got.Messages[1+2*i], got.Messages[2+2*i]
		if user.Role != "user" || assistant.Role != "assistant" {
			t.Fatalf("example %d roles = %q/%q, want user/assistant", i, user.Role, assistant.Role)
		}
		// Generated, not hand-written: this is what keeps the demonstration honest.
		if user.Content != userMessage(e.req) {
			t.Fatalf("example %d user message = %q, not built by userMessage", i, user.Content)
		}
		if assistant.Content != e.out {
			t.Fatalf("example %d answer = %q, want %q", i, assistant.Content, e.out)
		}
	}
	last := got.Messages[wantLen-1]
	if last.Role != "user" || last.Content != userMessage(real) {
		t.Fatalf("last message = %q (%s), want the real request as a user turn", last.Content, last.Role)
	}
}

// The two-line shape (no 摘要) is the one that failed in production, so it has to
// stay demonstrated — a refactor that "tidies" the examples down to one must not
// silently drop the case the feature was fixed for.
func TestExamplesCoverBothMessageShapes(t *testing.T) {
	var withSummary, withoutSummary bool
	for _, e := range examplePairs {
		if strings.Contains(userMessage(e.req), "摘要：") {
			withSummary = true
		} else {
			withoutSummary = true
		}
		// An example answer that echoed a label would teach the failure.
		if got := clean(e.out, e.req.Title); got != e.out {
			t.Errorf("example answer %q does not survive clean() (got %q)", e.out, got)
		}
	}
	if !withSummary || !withoutSummary {
		t.Fatalf("examples cover withSummary=%v withoutSummary=%v; want both", withSummary, withoutSummary)
	}
}

// The labelled user message reads as a form, and models fill forms in. The
// demonstration turns above make that unlikely; this bounds it when it happens
// anyway. The first case is a real row from the deployed DB, which rendered as
// "来源：Hacker News 标题：网页服务器…" once the newline collapsed in HTML.
func TestCleanDropsEchoedPromptLabels(t *testing.T) {
	cases := []struct{ name, raw, in, want string }{{
		name: "echoed 来源 line is dropped, 标题 line is the answer",
		raw:  "来源：Hacker News\n标题：网页服务器部署模式在业余规模下行不通",
		in:   "The web server deployment model breaks at hobby scale",
		want: "网页服务器部署模式在业余规模下行不通",
	}, {
		name: "echoed 摘要 line is dropped too",
		raw:  "摘要：The new chip is 40% faster than the M4.\n标题：苹果发布 M5 芯片",
		in:   "Apple unveils M5 chip",
		want: "苹果发布 M5 芯片",
	}, {
		name: "the label alone on one line",
		raw:  "标题：苹果发布 M5 芯片",
		in:   "Apple unveils M5 chip",
		want: "苹果发布 M5 芯片",
	}, {
		// A model mirroring the shape need not mirror the punctuation width.
		name: "ASCII colon",
		raw:  "标题: 苹果发布 M5 芯片",
		in:   "Apple unveils M5 chip",
		want: "苹果发布 M5 芯片",
	}, {
		// The label is stripped before the wrapper, or unwrapQuotes never sees a pair.
		name: "quoted answer behind a label",
		raw:  "标题：“苹果发布 M5 芯片”",
		in:   "Apple unveils M5 chip",
		want: "苹果发布 M5 芯片",
	}, {
		name: "commentary appended below the headline is dropped",
		raw:  "苹果发布 M5 芯片\n\n（注：M5 是苹果的新一代芯片）",
		in:   "Apple unveils M5 chip",
		want: "苹果发布 M5 芯片",
	}, {
		// A colon inside a headline is punctuation; only the labels we send are labels.
		name: "a headline with its own colon survives",
		raw:  "苹果 M5 芯片：目前已知的全部信息",
		in:   "Apple's M5 Chip: Everything We Know So Far",
		want: "苹果 M5 芯片：目前已知的全部信息",
	}}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := clean(c.raw, c.in); got != c.want {
				t.Fatalf("clean(%q) = %q, want %q", c.raw, got, c.want)
			}
		})
	}
}

// A model that explains itself instead of translating must not have its essay
// stored as a headline. Returning "" settles the row without retrying.
func TestCleanRejectsRunawayAnswer(t *testing.T) {
	in := "Apple unveils M5 chip"
	essay := strings.Repeat("这句话是对该标题的详细解释。", 40)
	if got := clean(essay, in); got != "" {
		t.Fatalf("runaway answer was accepted (%d runes)", len([]rune(got)))
	}
}

func TestCleanTruncates(t *testing.T) {
	in := strings.Repeat("a", maxTitleRunes)
	out := clean(strings.Repeat("好", maxTitleRunes+50), in)
	if n := len([]rune(out)); n != maxTitleRunes {
		t.Fatalf("len = %d, want %d", n, maxTitleRunes)
	}
}

// The user message is the only channel feed content travels in, and the system
// prompt refers to its labels ("only the 标题 line is the task"), so the shape is
// part of the contract rather than formatting.
func TestUserMessageCarriesContext(t *testing.T) {
	got := userMessage(Request{
		Title:    "Apple unveils M5 chip",
		FeedName: "Hacker News",
		Summary:  "The new chip is 40% faster than the M4.",
	})
	want := "来源：Hacker News\n摘要：The new chip is 40% faster than the M4.\n标题：Apple unveils M5 chip"
	if got != want {
		t.Fatalf("userMessage =\n%q\nwant\n%q", got, want)
	}
	// The title is last: it is the thing to act on, and trailing position is the
	// most reliable place to put it.
	if !strings.HasSuffix(got, "标题：Apple unveils M5 chip") {
		t.Fatal("the title is not the last line")
	}
}

// A feed with no context must produce the same bare request this made before the
// feature existed — no empty labels for the model to interpret.
func TestUserMessageOmitsEmptyContext(t *testing.T) {
	got := userMessage(Request{Title: "Apple unveils M5 chip"})
	if got != "标题：Apple unveils M5 chip" {
		t.Fatalf("userMessage = %q", got)
	}
}

func TestSummaryContext(t *testing.T) {
	cases := []struct {
		name, summary, title, want string
	}{{
		// article_states usually holds a stripped snippet already, but atom's raw
		// <summary> fallback is not stripped, so tags must not reach the prompt.
		name:    "strips tags",
		summary: "<p>The new chip is <b>40%</b> faster.</p>",
		want:    "The new chip is 40% faster.",
	}, {
		// Newlines would compete with the line-per-label structure above.
		name:    "collapses whitespace",
		summary: "The new chip\n\n  is faster.",
		want:    "The new chip is faster.",
	}, {
		// Link-blog feeds routinely set summary = title. Sending it back is pure
		// cost and tells the model nothing it is not already looking at.
		name:    "drops a repeat of the title",
		summary: "Apple unveils M5 chip",
		title:   "Apple unveils M5 chip",
		want:    "",
	}, {
		name:    "drops an empty summary",
		summary: "   ",
		want:    "",
	}, {
		// Hacker News' <description> is `<a href="…">Comments</a>`. Labelling that
		// 摘要： is worse than no context: it is noise in the channel meant to carry
		// meaning, on the feed whose headlines need context most.
		name:    "drops boilerplate too short to disambiguate",
		summary: `<a href="https://news.ycombinator.com/item?id=1">Comments</a>`,
		want:    "",
	}, {
		name:    "keeps a summary just over the floor",
		summary: "A short but real précis.",
		want:    "A short but real précis.",
	}}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := summaryContext(c.summary, c.title); got != c.want {
				t.Fatalf("summaryContext = %q, want %q", got, c.want)
			}
		})
	}
}

// The summary is the only near-unbounded input; some feeds put the whole article
// body in it.
func TestSummaryContextTruncates(t *testing.T) {
	got := summaryContext(strings.Repeat("长", maxSummaryRunes+100), "t")
	if n := len([]rune(got)); n != maxSummaryRunes {
		t.Fatalf("len = %d, want %d", n, maxSummaryRunes)
	}
}

// clean's growth check must keep measuring against the title. Measuring against
// the whole prompt would let a model that was talked into echoing the summary
// store the body as a headline.
func TestCleanGrowthIgnoresSummaryLength(t *testing.T) {
	title := "Apple unveils M5 chip"
	body := strings.Repeat("这是被回显的正文内容。", 40)
	if got := clean(body, title); got != "" {
		t.Fatalf("an echoed body was accepted as a headline (%d runes)", len([]rune(got)))
	}
}

// The system prompt is the cacheable prefix. Under DeepSeek's 64-token block
// floor it never caches at all, which is what the previous 53-token prompt hit.
// Runes are a proxy, but a coarse one is enough to catch a rewrite that shrinks
// it back under.
func TestSystemPromptClearsCacheFloor(t *testing.T) {
	if n := len([]rune(systemPrompt)); n < 200 {
		t.Fatalf("system prompt is %d runes; too short to reach a prefix-cache block", n)
	}
}

func TestValidateBaseURL(t *testing.T) {
	ok := []string{
		"https://api.deepseek.com",
		"https://api.moonshot.cn/v1",
		"http://127.0.0.1:11434/v1",
		"http://localhost:8000/v1",
	}
	for _, u := range ok {
		if err := ValidateBaseURL(u); err != nil {
			t.Errorf("ValidateBaseURL(%q) = %v, want nil", u, err)
		}
	}
	bad := []string{
		"http://example.com",     // plaintext to a remote host
		"http://169.254.169.254", // cloud metadata over plaintext
		"ftp://api.deepseek.com",
		"not a url",
		"",
	}
	for _, u := range bad {
		if err := ValidateBaseURL(u); err == nil {
			t.Errorf("ValidateBaseURL(%q) = nil, want an error", u)
		}
	}
}

func TestEndpointJoin(t *testing.T) {
	cases := map[string]string{
		"https://api.deepseek.com":   "https://api.deepseek.com/chat/completions",
		"https://api.moonshot.cn/v1": "https://api.moonshot.cn/v1/chat/completions",
		"http://127.0.0.1:11434/v1/": "http://127.0.0.1:11434/v1/chat/completions",
	}
	for in, want := range cases {
		if got := endpoint(in); got != want {
			t.Errorf("endpoint(%q) = %q, want %q", in, got, want)
		}
	}
}

// serve stands up a fake OpenAI-compatible endpoint.
func serve(t *testing.T, status int, body string) Config {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
		_, _ = w.Write([]byte(body))
	}))
	t.Cleanup(srv.Close)
	return Config{BaseURL: srv.URL, APIKey: "sk-test", Model: "m"}
}

func TestTranslateReadsChoice(t *testing.T) {
	cfg := serve(t, http.StatusOK,
		`{"choices":[{"message":{"role":"assistant","content":"苹果发布 M5 芯片"}}]}`)
	got, err := New(nil).Translate(context.Background(), cfg, Request{Title: "Apple unveils M5 chip"})
	if err != nil {
		t.Fatalf("Translate: %v", err)
	}
	if got != "苹果发布 M5 芯片" {
		t.Fatalf("got %q", got)
	}
}

// No choices is "the endpoint answered but gave nothing usable": empty string,
// nil error, so the caller settles the row instead of retrying forever.
func TestTranslateEmptyChoicesIsNotAnError(t *testing.T) {
	cfg := serve(t, http.StatusOK, `{"choices":[]}`)
	got, err := New(nil).Translate(context.Background(), cfg, Request{Title: "Apple unveils M5 chip"})
	if err != nil || got != "" {
		t.Fatalf("got (%q, %v), want (\"\", nil)", got, err)
	}
}

// Status mapping exists so the settings panel can say something specific while
// the upstream body never reaches the browser.
func TestTranslateNormalizesStatuses(t *testing.T) {
	cases := []struct {
		status int
		want   error
	}{
		{http.StatusUnauthorized, ErrAuth},
		{http.StatusForbidden, ErrAuth},
		{http.StatusNotFound, ErrModel},
		{http.StatusBadRequest, ErrModel},
		{http.StatusInternalServerError, ErrUpstream},
	}
	for _, c := range cases {
		cfg := serve(t, c.status, `{"error":{"message":"secret upstream detail"}}`)
		_, err := New(nil).Translate(context.Background(), cfg, Request{Title: "Apple unveils M5 chip"})
		if !errors.Is(err, c.want) {
			t.Errorf("status %d → %v, want %v", c.status, err, c.want)
		}
		if err != nil && strings.Contains(err.Error(), "secret upstream detail") {
			t.Errorf("status %d leaked the upstream body: %v", c.status, err)
		}
	}
}

func TestConfigReady(t *testing.T) {
	full := Config{BaseURL: "https://x", APIKey: "k", Model: "m"}
	if !full.Ready() {
		t.Fatal("full config not ready")
	}
	// An empty key is how the feature is switched off.
	noKey := full
	noKey.APIKey = ""
	if noKey.Ready() {
		t.Fatal("config with no key reported ready")
	}
}

// Thinking is off by default on DeepSeek at `high` effort, which measured ~1800
// characters of reasoning to produce a ~20-character headline — 95% of the
// completion tokens. The switch has to be on the wire, and max_tokens rides with
// it (only safe once thinking is off).
func TestTranslateDisablesThinking(t *testing.T) {
	var got map[string]any
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewDecoder(r.Body).Decode(&got)
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"choices":[{"message":{"content":"苹果发布 M5 芯片"}}]}`))
	}))
	defer srv.Close()
	cfg := Config{BaseURL: srv.URL, APIKey: "sk-test", Model: "m"}

	if _, err := New(nil).Translate(context.Background(), cfg, Request{Title: "Apple unveils M5 chip"}); err != nil {
		t.Fatalf("Translate: %v", err)
	}
	thinking, ok := got["thinking"].(map[string]any)
	if !ok || thinking["type"] != "disabled" {
		t.Fatalf(`thinking = %v, want {"type":"disabled"}`, got["thinking"])
	}
	if got["max_tokens"] != float64(maxCompletionTokens) {
		t.Fatalf("max_tokens = %v, want %d", got["max_tokens"], maxCompletionTokens)
	}
}

// `thinking` is DeepSeek's field. A provider that rejects unknown fields answers
// 400, and the only honest reading is "one of these is not understood" — so the
// call retries without them instead of reporting the model as unavailable.
// max_tokens must come off too: with thinking back on, a low cap truncates the
// model mid-thought and returns empty content, which the caller would settle as
// "no translation, never retry".
func TestTranslateRetriesWithoutThinkingOn400(t *testing.T) {
	var bodies []map[string]any
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var b map[string]any
		_ = json.NewDecoder(r.Body).Decode(&b)
		bodies = append(bodies, b)
		w.Header().Set("Content-Type", "application/json")
		if _, sent := b["thinking"]; sent {
			w.WriteHeader(http.StatusBadRequest)
			_, _ = w.Write([]byte(`{"error":{"message":"unknown field: thinking"}}`))
			return
		}
		_, _ = w.Write([]byte(`{"choices":[{"message":{"content":"苹果发布 M5 芯片"}}]}`))
	}))
	defer srv.Close()
	cfg := Config{BaseURL: srv.URL, APIKey: "sk-test", Model: "m"}

	got, err := New(nil).Translate(context.Background(), cfg, Request{Title: "Apple unveils M5 chip"})
	if err != nil {
		t.Fatalf("Translate: %v", err)
	}
	if got != "苹果发布 M5 芯片" {
		t.Fatalf("got %q", got)
	}
	if len(bodies) != 2 {
		t.Fatalf("want 2 attempts, got %d", len(bodies))
	}
	if _, sent := bodies[1]["thinking"]; sent {
		t.Fatal("retry still carried the thinking field")
	}
	if _, sent := bodies[1]["max_tokens"]; sent {
		t.Fatal("retry still carried max_tokens; it would truncate the reasoning")
	}
}

// A 400 that is not about the request fields still ends as ErrModel after the
// retry, rather than looping.
func TestTranslateGivesUpWhenRetryAlso400s(t *testing.T) {
	calls := 0
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		calls++
		w.WriteHeader(http.StatusBadRequest)
	}))
	defer srv.Close()
	cfg := Config{BaseURL: srv.URL, APIKey: "sk-test", Model: "nope"}

	_, err := New(nil).Translate(context.Background(), cfg, Request{Title: "Apple unveils M5 chip"})
	if !errors.Is(err, ErrModel) {
		t.Fatalf("err = %v, want ErrModel", err)
	}
	if calls != 2 {
		t.Fatalf("want exactly 2 attempts, got %d", calls)
	}
}
