#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/loc.md"

# Sum the line counts of NUL-separated file paths read from stdin (0 if none).
count() {
  local total=0 file
  while IFS= read -r -d '' file; do
    total=$((total + $(wc -l < "$file")))
  done
  echo "$total"
}

# Backend: TypeScript run natively by Node. Tests (*.test.ts + *.itest.ts) live in server/test/;
# slog is vendored.
backend_src=$(find "$REPO/server" -name "*.ts" \
              ! -path "*/test/*" ! -path "*/node_modules/*" ! -path "*/vendor/*" -print0 | count)
backend_test=$(find "$REPO/server/test" -name "*.ts" -print0 | count)
backend_vendor=$(find "$REPO/server/vendor" -name "*.ts" -print0 | count)

# Frontend: Vite + React (.tsx/.ts) plus CSS.
frontend_src=$(find "$REPO/client/src" \( -name "*.tsx" -o -name "*.ts" -o -name "*.css" \) \
               ! -name "*.test.tsx" ! -name "*.test.ts" ! -path "*/__tests__/*" -print0 | count)
frontend_test=$(find "$REPO/client/src" \( -name "*.test.tsx" -o -name "*.test.ts" \) -print0 | count)

total=$((backend_src + backend_test + backend_vendor + frontend_src + frontend_test))

{
  echo "# Lines of Code"
  echo ""
  echo "> Generated by \`scripts/loc.sh\` on $(date '+%Y-%m-%d')"
  echo ""
  echo "| Section | Lines |"
  echo "|---------|------:|"
  echo "| Backend — source   | $backend_src    |"
  echo "| Backend — tests    | $backend_test   |"
  echo "| Backend — vendored | $backend_vendor |"
  echo "| Frontend — source  | $frontend_src   |"
  echo "| Frontend — tests   | $frontend_test  |"
  echo "| **Total**          | **$total**      |"
} > "$OUT"

echo "Written to $OUT"
